# .goreleaser.yml
version: 2

# Opcional: defina o nome do projeto se necessário
project_name: pseudonymization-lgpd-tools

builds:
- id: pseudonymization-lgpd-tools
  main: ./examples/how-to-use.go
  binary: pseudonymization-lgpd-tools
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  - arm
  skip: true

release:
  # Opcional: você pode remover a seção 'github' se o repositório 
  # no qual você está executando a action for o 'raywall/pseudonymization-lgpd-tools'.
  # GoReleaser infere isso automaticamente.
  name_template: "Release {{ .Tag }}"
  github:
    owner: raywall
    name: pseudonymization-lgpd-tools
  make_latest: true

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'Merge pull request'
    - 'Merge branch'
